-- MySQL Script generated by MySQL Workbench
-- Thu Aug 18 12:15:53 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Diagrama_curso
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Diagrama_curso` ;

-- -----------------------------------------------------
-- Schema Diagrama_curso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Diagrama_curso` DEFAULT CHARACTER SET utf8 ;
USE `Diagrama_curso` ;

-- -----------------------------------------------------
-- Table `Diagrama_curso`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_curso`.`Usuarios` (
  `idUsuario` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `N°_celular` VARCHAR(11) NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_curso`.`Mis RRSS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_curso`.`Mis RRSS` (
  `idUsuario` INT NOT NULL,
  `idSocialMedia` INT NULL,
  `Mi_whatsapp` VARCHAR(45) NULL,
  `Mi_correo` VARCHAR(45) NULL,
  `Mi_instagram` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY ()
    REFERENCES `Diagrama_curso`.`Usuarios` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_curso`.`Chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_curso`.`Chat` (
  `idUsuario` INT NOT NULL,
  `idChat` INT NULL,
  `Mi_whatsapp` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY ()
    REFERENCES `Diagrama_curso`.`Usuarios` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Mi_whatsapp`
    FOREIGN KEY ()
    REFERENCES `Diagrama_curso`.`Mis RRSS` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Diagrama_curso`.`Opciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Diagrama_curso`.`Opciones` (
  `idUsuario` INT NOT NULL,
  `About_me` VARCHAR(45) NOT NULL,
  `My_skills` VARCHAR(45) NULL,
  `IdSocialMedia` INT NULL,
  `Follow_me` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Diagrama_curso`.`Usuarios` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSocialMedia`
    FOREIGN KEY ()
    REFERENCES `Diagrama_curso`.`Mis RRSS` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
